### ISSUE TITLE
Failed: EventsBySliceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-r2dbc#118]
Against Yugabyte

```
 - should retrieve from several slices *** FAILED *** (12 seconds, 948 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds. (EventsBySliceSpec.scala:338)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at akka.persistence.r2dbc.query.EventsBySliceSpec$$anon$8.<init>(EventsBySliceSpec.scala:338)
[info]   at akka.persistence.r2dbc.query.EventsBySliceSpec.$anonfun$new$25(EventsBySliceSpec.scala:296)
```
[logs_220.zip](https://github.com/akka/akka-persistence-r2dbc/files/7475843/logs_220.zip)

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4106845087?check_suite_focus=true#step:7:2534

**Comment by patriknw** [comment]
not sure it has been fixed, but closing until seen again
