### ISSUE TITLE
Flaky DurableStateEndToEndSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka-persistence-r2dbc#139]
Seen at https://github.com/akka/akka-persistence-r2dbc/runs/4157477944?check_suite_focus=true#step:7:8286

```scala
[info] - must handle latest updated state exactlyOnce *** FAILED *** (16 seconds, 138 milliseconds)
[info]   projectionId ProjectionId(f030042a-e8c0-4a89-8a0e-bcaf9db94a88, 64-95), persistenceId PersistenceId(TestEntity-4|p1), slice 95: The code passed to eventually never returned normally. Attempted 109 times over 10.037617700999999 seconds. Last failure message: empty.tail. (DurableStateEndToEndSpec.scala:232)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.enablers.Retrying$$anon$4.tryTryAgain$2(Retrying.scala:185)
[info]   at org.scalatest.enablers.Retrying$$anon$4.retry(Retrying.scala:192)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:402)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:401)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.eventually(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.projection.r2dbc.DurableStateEndToEndSpec.$anonfun$new$10(DurableStateEndToEndSpec.scala:232)
[info]   at org.scalatest.Assertions.withClue(Assertions.scala:1065)
[info]   at org.scalatest.Assertions.withClue$(Assertions.scala:1052)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.withClue(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.projection.r2dbc.DurableStateEndToEndSpec.$anonfun$new$9(DurableStateEndToEndSpec.scala:231)
[info]   at akka.projection.r2dbc.DurableStateEndToEndSpec.$anonfun$new$9$adapted(DurableStateEndToEndSpec.scala:224)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:190)
[info]   at akka.projection.r2dbc.DurableStateEndToEndSpec.$anonfun$new$8(DurableStateEndToEndSpec.scala:224)
[info]   at akka.projection.r2dbc.DurableStateEndToEndSpec.$anonfun$new$8$adapted(DurableStateEndToEndSpec.scala:223)
[info]   at scala.collection.immutable.Map$Map4.foreach(Map.scala:571)
[info]   at akka.projection.r2dbc.DurableStateEndToEndSpec.$anonfun$new$2(DurableStateEndToEndSpec.scala:223)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

**Comment by octonato** [comment]
Once more here: https://github.com/akka/akka-persistence-r2dbc/runs/4189492256?check_suite_focus=true#step:7:8383

**Comment by patriknw** [comment]
This one is super weird. It stored the 200 states ok, but it's only finding and processing 4.

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4332099961?check_suite_focus=true#step:7:1059

**Comment by patriknw** [comment]
In a failure today the root cause was:
```
2022-01-09T19:43:01.1815018Z [2022-01-09 19:42:44,023] [INFO] [akka.persistence.r2dbc.state.scaladsl.DurableStateDao] [] [] [reactor-tcp-epoll-3] - select [TestEntity-5|p0] - getConnection took [1207491] µs
2022-01-09T19:43:01.1818141Z [2022-01-09 19:42:44,208] [INFO] [akka.persistence.r2dbc.state.scaladsl.DurableStateDao] [] [] [reactor-tcp-epoll-4] - select [TestEntity-5|p14] - getConnection took [1383935] µs
2022-01-09T19:43:01.1824011Z [2022-01-09 19:42:44,211] [WARN] [io.r2dbc.postgresql.client.ReactorNettyClient] [] [] [reactor-tcp-epoll-2] - Notice: SEVERITY_LOCALIZED=WARNING, SEVERITY_NON_LOCALIZED=WARNING, CODE=57P02, MESSAGE=terminating connection because of crash of another server process, DETAIL=The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory., HINT=In a moment you should be able to reconnect to the database and repeat your command., FILE=postgres.c, LINE=2680, ROUTINE=quickdie
2022-01-09T19:43:01.1835523Z [2022-01-09 19:42:44,211] [WARN] [io.r2dbc.postgresql.client.ReactorNettyClient] [] [] [reactor-tcp-epoll-1] - Notice: SEVERITY_LOCALIZED=WARNING, SEVERITY_NON_LOCALIZED=WARNING, CODE=57P02, MESSAGE=terminating connection because of crash of another server process, DETAIL=The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory., HINT=In a moment you should be able to reconnect to the database and repeat your command., FILE=postgres.c, LINE=2680, ROUTINE=quickdie
2022-01-09T19:43:01.1848968Z [2022-01-09 19:42:44,211] [WARN] [io.r2dbc.postgresql.client.ReactorNettyClient] [] [] [reactor-tcp-epoll-4] - Notice: SEVERITY_LOCALIZED=WARNING, SEVERITY_NON_LOCALIZED=WARNING, CODE=57P02, MESSAGE=terminating connection because of crash of another server process, DETAIL=The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory., HINT=In a moment you should be able to reconnect to the database and repeat your command., FILE=postgres.c, LINE=2680, ROUTINE=quickdie
2022-01-09T19:43:01.1858859Z [2022-01-09 19:42:44,212] [WARN] [io.r2dbc.postgresql.client.ReactorNettyClient] [] [] [reactor-tcp-epoll-3] - Notice: SEVERITY_LOCALIZED=WARNING, SEVERITY_NON_LOCALIZED=WARNING, CODE=57P02, MESSAGE=terminating connection because of crash of another server process, DETAIL=The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory., HINT=In a moment you should be able to reconnect to the database and repeat your command., FILE=postgres.c, LINE=2680, ROUTINE=quickdie
2022-01-09T19:43:01.1864955Z [2022-01-09 19:42:44,212] [WARN] [io.r2dbc.postgresql.client.ReactorNettyClient] [] [] [reactor-tcp-epoll-1] - Notice: SEVERITY_LOCALIZED=WARNING, SEVERITY_NON_LOCALIZED=WARNING, CODE=57P02, MESSAGE=terminating connection because of crash of another server process, DETAIL=The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory., HINT=In a moment you should be able to reconnect to the database and repeat your command., POSITION=330, FILE=postgres.c, LINE=2680, ROUTINE=quickdie
```

I have tried to increase the shm memory in https://github.com/akka/akka-persistence-r2dbc/pull/168

**Comment by patriknw** [comment]
Haven't seen in a while
