### ISSUE TITLE
failure: R2dbcTimestampOffsetStoreSpec - save TimestampOffset when same timestamp

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#173]
https://github.com/akka/akka-persistence-r2dbc/runs/4444519616?check_suite_focus=true#step:7:378

```
[info] - must save TimestampOffset when same timestamp *** FAILED *** (14 milliseconds)
379
[info]   Some(TimestampOffset(2021-12-07T13:35:20.800Z,1970-01-01T00:00:00Z,Map(p4 -> 9, p2 -> 1, p3 -> 5, p1 -> 3))) was not equal to Some(TimestampOffset(2021-12-07T13:35:20.800Z,1970-01-01T00:00:00Z,Map(p1 -> 3, p2 -> 2, p3 -> 5, p4 -> 9))) (R2dbcTimestampOffsetStoreSpec.scala:155)
380
[info]   org.scalatest.exceptions.TestFailedException:
381
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:339)
382
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6982)
383
[info]   at akka.projection.r2dbc.R2dbcTimestampOffsetStoreSpec.$anonfun$new$4(R2dbcTimestampOffsetStoreSpec.scala:155)
384
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
385
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
386
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
387
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
388
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
389
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1076)
390
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture(LogCapturing.scala:70)
391
[info]   at akka.actor.testkit.typed.scaladsl.LogCapturing.withFixture$(LogCapturing.scala:68)
392
[info]   at akka.projection.r2dbc.R2dbcTimestampOffsetStoreSpec.withFixture(R2dbcTimestampOffsetStoreSpec.scala:47)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4702105858?check_suite_focus=true#step:7:389

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4758171226?check_suite_focus=true#step:7:371

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/runs/4953715268?check_suite_focus=true
