### ISSUE TITLE
Failed: EventsBySliceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-r2dbc#234]
```
[info] - should retrieve from several slices *** FAILED *** (12 seconds, 295 milliseconds)
[1624](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1624)
[info]   A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds. (EventsBySliceSpec.scala:373)
[1625](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1625)
[info]   org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2:
[1626](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1626)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:339)
[1627](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1627)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[1628](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1628)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
[1629](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1629)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[1630](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1630)
[info]   at akka.persistence.r2dbc.query.EventsBySliceSpec$$anon$10.<init>(EventsBySliceSpec.scala:373)
[1631](https://github.com/akka/akka-persistence-r2dbc/runs/6253686705?check_suite_focus=true#step:7:1631)
[info]   at akka.persistence.r2dbc.query.EventsBySliceSpec.$anonfun$new$30(EventsBySliceSpec.scala:331)
```
[logs_598.zip](https://github.com/akka/akka-persistence-r2dbc/files/8601588/logs_598.zip)

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3656258723/jobs/6178495927#step:7:1657

**Comment by patriknw** [comment]
Might be fixed by https://github.com/akka/akka-persistence-r2dbc/pull/438
