### ISSUE TITLE
Rejected envelope from backtracking

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#245]
```
[2022-06-02 10:01:40,705] [WARN] [akka.projection.r2dbc.internal.R2dbcOffsetStore] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-16] - Rejecting unexpected sequence number [1] for pid [ShoppingCart|20220602-081454.1654150494-115], previous sequence number [7]. Offset: TimestampOffset(2022-06-02T06:14:54.854098Z,1970-01-01T00:00:00Z,Map(ShoppingCart|20220602-081454.1654150494-115 -> 1))
[2022-06-02 10:01:40,711] [ERROR] [akka.projection.r2dbc.internal.R2dbcProjectionImpl$R2dbcInternalProjectionState] [akka://ShoppingAnalyticsService@127.0.0.1:3551] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-3] - [cart-events-ShoppingCart-768-1023] Failed to process envelope with offset [TimestampOffset(2022-06-02T06:14:54.854098Z,1970-01-01T00:00:00Z,Map(ShoppingCart|20220602-081454.1654150494-115 -> 1))]. Projection will stop as defined by recovery strategy.
java.lang.IllegalStateException: Rejected envelope from backtracking, persistenceId [ShoppingCart|20220602-081454.1654150494-115], seqNr [1] due to unexpected sequence number. Please report this issue at https://github.com/akka/akka-persistence-r2dbc
	at akka.projection.r2dbc.internal.R2dbcOffsetStore.isAccepted(R2dbcOffsetStore.scala:673)
	at akka.projection.r2dbc.internal.R2dbcOffsetStore.isAccepted(R2dbcOffsetStore.scala:591)
```

Looking at the code in `isAccepted` it passes the `isDuplicate` check so maybe related to `currentInflight`. It's an `atLeastOnceAsync` projection.

**Comment by patriknw** [comment]
I think this has to do with the eviction of old records. Probably the same reason that is causing the unique constraint violations.

```
io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23505] duplicate key value violates unique constraint "akka_projection_timestamp_offset_store_pkey"
```
