### ISSUE TITLE
Failed: DurableStateBySliceSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-r2dbc#289]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:220

```
[info] - should emit DeletedDurableState for latest deleted state *** FAILED *** (3 seconds, 73 milliseconds)
[220](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:221)
[info]   java.lang.AssertionError: Timeout (3 seconds) during receiveMessage while waiting for message.
[221](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:222)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[222](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:223)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessage_internal$1(TestProbeImpl.scala:182)
[223](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:224)
[info]   at scala.Option.getOrElse(Option.scala:201)
[224](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:225)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage_internal(TestProbeImpl.scala:182)
[225](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:226)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage(TestProbeImpl.scala:175)
[226](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:227)
[info]   at akka.persistence.r2dbc.state.DurableStateBySliceSpec$$anon$3.<init>(DurableStateBySliceSpec.scala:190)
[227](https://github.com/akka/akka-persistence-r2dbc/actions/runs/3274035196/jobs/5387865925#step:7:228)
[info]   at akka.persistence.r2dbc.state.DurableStateBySliceSpec.$anonfun$new$9(DurableStateBySliceSpec.scala:173)
```

Full logs: 
[1_Run test with Postgres.txt](https://github.com/akka/akka-persistence-r2dbc/files/9811783/1_Run.test.with.Postgres.txt)

**Comment by patriknw** [comment]
seems flaky: https://github.com/akka/akka-persistence-r2dbc/actions/runs/3295788742/jobs/5434698058#step:7:220

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3320540638/jobs/5487044057

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3496981693/jobs/5855529665#step:7:220

**Comment by patriknw** [comment]
This is failing because of bug https://github.com/akka/akka/pull/31753
