### ISSUE TITLE
Duplicate key in projection

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-r2dbc#295]
Consumer error:

```
[info] [2022-10-24 15:36:04,840] [WARN] [akka.stream.scaladsl.RestartWithBackoffSource] [akka://ShoppingAnalyticsService@127.0.0.1:3551] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-28] - Restarting stream due to failure [1]: io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23505] duplicate key value violates unique constraint "akka_projection_timestamp_offset_store_pkey"
[info] io.r2dbc.postgresql.ExceptionFactory$PostgresqlDataIntegrityViolationException: [23505] duplicate key value violates unique constraint "akka_projection_timestamp_offset_store_pkey"
[info] 	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:102)
[info] 	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:65)
[info] 	at io.r2dbc.postgresql.ExceptionFactory.handleErrorResponse(ExceptionFactory.java:132)
[info] 	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:176)
```

From postgres log:
```
postgres_db  | 2022-10-24 13:36:04.833 UTC [93] ERROR:  duplicate key value violates unique constraint "akka_projection_timestamp_offset_store_pkey"
postgres_db  | 2022-10-24 13:36:04.833 UTC [93] DETAIL:  Key (slice, projection_name, timestamp_offset, persistence_id, seq_nr)=(256, cart-events, 2022-10-24 15:35:25.569941+02, ShoppingCart|999cf296-8151-4b58-8ff8-4bbc5639ec9b, 7) already exists.
postgres_db  | 2022-10-24 13:36:04.833 UTC [93] STATEMENT:  INSERT INTO akka_projection_timestamp_offset_store (projection_name, projection_key, slice, persistence_id, seq_nr, timestamp_offset, timestamp_consumed) VALUES ($1,$2,$3,$4,$5,$6, transaction_timestamp())
```

`999cf296-8151-4b58-8ff8-4bbc5639ec9b` occurs a couple of times earlier in the log, but note - no lazy load or anything:
```
[info] [2022-10-24 15:36:04,299] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-5] - Projection [cart-events-cart-256-512] consumed ItemAdded for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, added 1 t-shirt. Total [331] events.
[info] [2022-10-24 15:36:04,300] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-28] - Projection [cart-events-cart-256-512] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 2 t-shirt. Total [333] events.
[info] [2022-10-24 15:36:04,300] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-29] - Projection [cart-events-cart-256-512] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 3 t-shirt. Total [335] events.
[info] [2022-10-24 15:36:04,301] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-31] - Projection [cart-events-cart-256-512] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 4 t-shirt. Total [337] events.
[info] [2022-10-24 15:36:04,301] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-27] - Projection [cart-events-cart-256-512] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 5 t-shirt. Total [339] events.
[info] [2022-10-24 15:36:04,301] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-28] - Projection [cart-events-cart-256-512] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 6 t-shirt. Total [341] events.
[info] [2022-10-24 15:36:04,302] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-17] - Projection [cart-events-cart-256-512] consumed CheckedOut for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b. Total [343] events.
[info] [2022-10-24 15:36:04,305] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-30] - Projection [cart-events-cart-0-256] consumed ItemAdded for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, added 1 t-shirt. Total [337] events.
[info] [2022-10-24 15:36:04,305] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-32] - Projection [cart-events-cart-0-256] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 2 t-shirt. Total [339] events.
[info] [2022-10-24 15:36:04,306] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-29] - Projection [cart-events-cart-0-256] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 3 t-shirt. Total [341] events.
[info] [2022-10-24 15:36:04,306] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-29] - Projection [cart-events-cart-0-256] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 4 t-shirt. Total [343] events.
[info] [2022-10-24 15:36:04,307] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-28] - Projection [cart-events-cart-0-256] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 5 t-shirt. Total [345] events.
[info] [2022-10-24 15:36:04,307] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-28] - Projection [cart-events-cart-0-256] consumed ItemQuantityAdjusted for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b, changed 6 t-shirt. Total [347] events.
[info] [2022-10-24 15:36:04,307] [DEBUG] [shopping.analytics.ShoppingCartEventConsumer] [] [] [ShoppingAnalyticsService-akka.actor.default-dispatcher-31] - Projection [cart-events-cart-0-256] consumed CheckedOut for cart 999cf296-8151-4b58-8ff8-4bbc5639ec9b. Total [349] events.
```

Also, last update is consumed `15:36:04,307`but the error doesn't happen until `15:36:04,840`, half a second later.

**Comment by johanandren** [comment]
Turns out this was the Akka Projection gRPC samples using wrong (overlapping) slice ranges
