### ISSUE TITLE
failed: EventSourcedChaosSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#322]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3533172986/jobs/5928460161#step:6:3113

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3584313360/jobs/6030822898#step:7:2537

```
[info] - must handle all events exactlyOnce *** FAILED *** (25 seconds, 318 milliseconds)
2537
[info]   java.lang.AssertionError: Timeout (15 seconds) during receiveMessage while waiting for message.
2538
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
2539
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessage_internal$1(TestProbeImpl.scala:182)
2540
[info]   at scala.Option.getOrElse(Option.scala:201)
2541
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage_internal(TestProbeImpl.scala:182)
2542
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage(TestProbeImpl.scala:179)
2543
[info]   at akka.projection.r2dbc.EventSourcedChaosSpec.$anonfun$new$7(EventSourcedChaosSpec.scala:195)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/3754402137/jobs/6378590934#step:6:2934

**Comment by johanandren** [comment]
yugabyte 

https://github.com/akka/akka-projection/actions/runs/13327156305/job/37222867643#step:7:2358

```
[Failed(java.lang.AssertionError: Timeout (15 seconds) during receiveMessage while waiting for message.)]
[info] - must handle all events exactlyOnce *** FAILED *** (40 seconds, 287 milliseconds)
[info]   java.lang.AssertionError: Timeout (15 seconds) during receiveMessage while waiting for message.
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessage_internal$1(TestProbeImpl.scala:182)
[info]   at scala.Option.getOrElse(Option.scala:201)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage_internal(TestProbeImpl.scala:182)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessage(TestProbeImpl.scala:179)
[info]   at akka.projection.r2dbc.EventSourcedChaosSpec.$anonfun$new$7(EventSourcedChaosSpec.scala:188)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[info]   at akka.projection.r2dbc.EventSourcedChaosSpec.verify$1(EventSourcedChaosSpec.scala:185)
[info]   at akka.projection.r2dbc.EventSourcedChaosSpec.$anonfun$new$15(EventSourcedChaosSpec.scala:293)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
[info]   at akka.projection.r2dbc.EventSourcedChaosSpec.$anonfun$new$2(EventSourcedChaosSpec.scala:223)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```
