### ISSUE TITLE
Projection stuck in mid-event log backtracking

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-r2dbc#343]
Testing gRPC transport for projections I ended up with (multiple cases of) the following:

On the consuming side:
```
Rejecting unknown sequence number [5] for pid [replicated-shopping-cart|a9b85a87-f170-47e1-8a97-504e26217e69|DCA]. Offset: TimestampOffset(2023-01-12T12:27:27.244543Z,1970-01-01T00:00:00Z,Map(replicated-shopping-cart|a9b85a87-f170-47e1-8a97-504e26217e69|DCA -> 5))

Restarting stream due to failure [1]: java.lang.IllegalStateException: Rejected envelope from backtracking, persistenceId [replicated-shopping-cart|a9b85a87-f170-47e1-8a97-504e26217e69|DCA], seqNr [5], due to unknown sequence number. Please report this issue at https://github.com/akka/akka-persistence-r2dbc
java.lang.IllegalStateException: Rejected envelope from backtracking, persistenceId [replicated-shopping-cart|a9b85a87-f170-47e1-8a97-504e26217e69|DCA], seqNr [5], due to unknown sequence number. Please report this issue at https://github.com/akka/akka-persistence-r2dbc
	at akka.projection.r2dbc.internal.R2dbcOffsetStore.$anonfun$isAccepted$5(R2dbcOffsetStore.scala:727)
	at akka.projection.r2dbc.internal.R2dbcOffsetStore.$anonfun$isAccepted$5$adapted(R2dbcOffsetStore.scala:706)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
```

No entries in the journal and no entries in the timestamp offset table for `a9b85a87-f170-47e1-8a97-504e26217e69` on the consuming side.

Looking in the journal on the producing side for `a9b85a87-f170-47e1-8a97-504e26217e69` I see 7 events persisted, `db_timestamp` for each:

1. at 12:27:27.076595+00
2. at 12:27:27.129595+00
3. at 12:27:27.140795+00
4. at 12:27:27.235386+00
5. at 12:27:27.244543+00
6. at 12:27:27.247372+00
7. at 12:27:27.3399+00

So we are not getting the events before seq_nr 5 for some reason.

## Logs

On the consumer side:
```
16:22:30.386 Projection [ProjectionId(replicated-shopping-cart_DCA, replicated-shopping-cart-DCA-512-767)] started in resumed mode.
16:22:30.422 readTimestampOffset state with [2049] persistenceIds, oldest [2023-01-12T11:59:51.648536Z], latest [2023-01-12T12:29:19.041190Z] 
16:22:30.422 Starting eventsBySlices stream from [34.75.225.153] [replicated-shopping-cart], slices [512 - 767], offset [2023-01-12T12:29:37.242322Z]
16:22:30.583 Rejecting unknown sequence number [5] for pid [replicated-shopping-cart|a9b85a87-f170-47e1-8a97-504e26217e69|DCA]. Offset: TimestampOffset(2023-01-12T12:27:27.244543Z,1970-01-01T00:00:00Z,Map(replicated-shopping-cart|a9b85a87-f170-47e1-8a97-504e26217e69|DCA -> 5))
16:22:30.583 estarting stream due to failure [1]: java.lang.IllegalStateException: Rejected ...
```

On the producer side:
```
16:22:30.441 Starting eventsBySlices stream [replicated-shopping-cart], [replicated-shopping-cart], slices [512 - 767], offset [2023-01-12T12:29:37.242322Z]
16:22:30.442 Starting eventsBySlices query from slices [512 - 767], from time [2023-01-12T12:29:37.242322Z].
16:22:30.485 eventsBySlices retrieved [22] event count buckets, with a total of [27852], from slices [512 - 767], from time [2023-01-12T12:27:27.242322Z]
16:22:30.486 Read [22] bucket counts from slices [512 - 767]
## this query start time is just between seq nr 4 and 5
16:22:30.486 eventsBySlices next query [1] in backtracking mode from slices [512 - 767], between time [2023-01-12T12:27:27.242322Z - 2023-01-12T12:27:40Z]. Found [0] rows in previous query. 
16:22:30.497 Read [1000] events from slices [512 - 767]
16:22:30.567 eventsBySlices next query [2] in backtracking mode from slices [512 - 767], between time [2023-01-12T12:27:33.453419Z - 2023-01-12T12:27:50Z]. Found [1000] rows in previous backtracking query.
16:22:30.638 Read [1000] events from slices [512 - 767] <- after consumer crashed
```

Backtracking is not tracking back long enough?

**Comment by johanandren** [comment]
Is it just that the backtracking.window was smaller than the amount of time one side is lagging behind the other?

**Comment by patriknw** [comment]
Um, so the consumer side had some offsets stored but not for the problematic pid? Sounds like you have found a valid reason for how this can happen. I'm not sure what we should do about it yet, but seems this can be reproduced with a minimal test case?

**Comment by patriknw** [comment]
we also have `akka.projection.r2dbc.offset-store.time-window = 5 minutes`, which controls when entries in the offset table are deleted.

**Comment by johanandren** [comment]
I don't understad this well enough to figure out how reach this state, and to create a minimal reproducer yet.

I increased the window to 4 minutes, and the projection moved forward a bit, but got stuck on new pids. I think that at least confirms that it is about how far back the query goes.

**Comment by johanandren** [comment]
Consumer side offset table has some 42k entries, replication worked up to some point.

**Comment by johanandren** [comment]
Bumped offset-store.time-window to 10m and bactracking.window to 9 and now the replicas started catching up without errors (possibly destroying the evidence about what was wrong :/ ).

**Comment by johanandren** [comment]
Even with that much window I still have one of the slices failing, so maybe enough evidence left to figure it out anyway.
