### ISSUE TITLE
Flaky failure in EventsBySlicePerfSpec

### ISSUE THREAD

**Issue by octonato** [akka/akka-persistence-r2dbc#53]
```
imeout (3 seconds) while expecting 20 messages (got 18))]
[info] - should retrieve from several slices *** FAILED *** (6 seconds, 621 milliseconds)
[info]   java.lang.AssertionError: timeout (3 seconds) while expecting 20 messages (got 18)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:399)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1(TestProbeImpl.scala:262)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.$anonfun$receiveMessages_internal$1$adapted(TestProbeImpl.scala:257)
[info]   at scala.collection.immutable.Range.map(Range.scala:59)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages_internal(TestProbeImpl.scala:257)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.receiveMessages(TestProbeImpl.scala:244)
[info]   at akka.persistence.r2dbc.query.EventsBySlicePerfSpec.$anonfun$new$2(EventsBySlicePerfSpec.scala:72)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
```

**Comment by octonato** [comment]
Confirmed. Running the tests and checking client connections...

```
postgres=# SELECT count(*) FROM pg_stat_activity;
 count 
-------
   105
(1 row)

```
