### ISSUE TITLE
failed: h2 EventSourcedCleanupSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#530]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/7998436382/job/21844592008#step:5:7924

```
[info] - must delete events for slice before timestamp *** FAILED *** (292 milliseconds)
[info]   0 was not equal to 5 (EventSourcedCleanupSpec.scala:432)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:7539)
[info]   at akka.persistence.r2dbc.cleanup.scaladsl.EventSourcedCleanupSpec.$anonfun$new$44(EventSourcedCleanupSpec.scala:432)
```

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/9410616857/job/25922553783#step:5:7971

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/9728653061/job/26849619312#step:5:7796

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/9728653061/job/26849619312#step:5:7796

**Comment by johanandren** [comment]
It is possible that the last failure was before that hardening was merged.
