### ISSUE TITLE
failed: EventsBySlicePubSubSpec: should turn FilteredPayload to filtered events with no payload

### ISSUE THREAD

**Issue by ennru** [akka/akka-persistence-r2dbc#546]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/8565523378/job/23473696096#step:7:1209

```
[info] - should turn FilteredPayload to filtered events with no payload *** FAILED *** (100 milliseconds)
[info]   java.lang.AssertionError: expected OnNext, found OnError(java.lang.IllegalArgumentException: Slice range [0-1023] spans over more than one of the [4] data partitions.
[info] 	at akka.persistence.r2dbc.internal.postgres.PostgresQueryDao.rowsBySlices(PostgresQueryDao.scala:227)
[info] 	at akka.persistence.r2dbc.internal.BySliceQuery.nextQuery$2(BySliceQuery.scala:459)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/11127532266/job/30920059443#step:7:1226
