### ISSUE TITLE
failed: Yugabyte EventSourcedCleanupSpec.scala

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-r2dbc#547]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/8609321429/job/23593065543#step:6:966

```
[info] - must delete events for slice before timestamp *** FAILED *** (146 milliseconds)
[info]   0 was not equal to 5 (EventSourcedCleanupSpec.scala:432)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:392)
[info]   at org.scalatest.matchers.should.Matchers.shouldBe(Matchers.scala:7017)
[info]   at org.scalatest.matchers.should.Matchers.shouldBe$(Matchers.scala:1808)
[info]   at akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit.shouldBe(ScalaTestWithActorTestKit.scala:31)
[info]   at akka.persistence.r2dbc.cleanup.scaladsl.EventSourcedCleanupSpec.f$proxy11$1(EventSourcedCleanupSpec.scala:432)
[info]   at akka.persistence.r2dbc.cleanup.scaladsl.EventSourcedCleanupSpec.$init$$$anonfun$1$$anonfun$11(EventSourcedCleanupSpec.scala:392)
```

[6_Run tests with Yugabyte (3.3, 1.17.0, temurin1.17.0, core_test).txt](https://github.com/akka/akka-persistence-r2dbc/files/14929450/6_Run.tests.with.Yugabyte.3.3.1.17.0.temurin1.17.0.core_test.txt)

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/9425426998/job/25967078695#step:6:972

**Comment by patriknw** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/9737111904/job/26868721831#step:6:1083

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/9737111904/job/26868721831#step:6:1083

**Comment by johanandren** [comment]
It is possible that the last failure was before that hardening was merged.
