### ISSUE TITLE
failed: EventsBySlicePubSubBacktrackingSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#629]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/11945455475/job/33298146548#step:6:1087

```
[Failed(java.lang.IllegalStateException: Event was not loaded. Use eventOption and load the event on demand with LoadEventQuery.)]
[info] - should publish events *** FAILED *** (3 seconds, 128 milliseconds)
[info]   java.lang.IllegalStateException: Event was not loaded. Use eventOption and load the event on demand with LoadEventQuery.
[info]   at akka.persistence.query.typed.EventEnvelope.event(EventEnvelope.scala:190)
[info]   at akka.persistence.r2dbc.query.EventsBySlicePubSubBacktrackingSpec$$anon$1.$anonfun$new$5(EventsBySlicePubSubBacktrackingSpec.scala:100)
[info]   at akka.persistence.r2dbc.query.EventsBySlicePubSubBacktrackingSpec$$anon$1.$anonfun$new$5$adapted(EventsBySlicePubSubBacktrackingSpec.scala:98)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:190)
[info]   at akka.persistence.r2dbc.query.EventsBySlicePubSubBacktrackingSpec$$anon$1.<init>(EventsBySlicePubSubBacktrackingSpec.scala:98)
[info]   at akka.persistence.r2dbc.query.EventsBySlicePubSubBacktrackingSpec.$anonfun$new$2(EventsBySlicePubSubBacktrackingSpec.scala:79)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-r2dbc/actions/runs/12960908352/job/36155423021#step:6:1186
