### ISSUE TITLE
Leak of Direct buffer memory when running tests without fork

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#73]
This is still a problem so we must continue using forked tests.

After about 3 full runs of `test` with the same sbt session:
```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:172)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:116)
	at io.r2dbc.postgresql.codec.IntegerCodec.lambda$doEncode$0(IntegerCodec.java:56)
```

Note that this can be because how sbt manages classloaders for tests and probably not a problem for a real application.

**Comment by patriknw** [comment]
Forking works ok, so let's close this
