### ISSUE TITLE
NotSerializableException: org.scalatest.matchers.should.Matchers$AWord

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-r2dbc#96]
There is a problem with the sbt/ScalaTest setup when running forked tests. 

It throws and logs weird things like:
```
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 26),A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds.,DurableStateBySliceSpec,akka.persistence.r2dbc.state.DurableStateBySliceSpec,Some(akka.persistence.r2dbc.state.DurableStateBySliceSpec),Live changesBySlices should retrieve from several slices,retrieve from several slices,Vector(),Vector(),Some(org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2: A timeout occurred waiting for a future to complete. Waited 10000000000 nanoseconds.),Some(10201),Some(IndentedText(- should retrieve from several slices,should retrieve from several slices,1)),Some(SeeStackDepthException),Some(akka.persistence.r2dbc.state.DurableStateBySliceSpec),None,pool-1-thread-1-ScalaTest-running-DurableStateBySliceSpec,1635406044954).
java.io.NotSerializableException: org.scalatest.matchers.should.Matchers$AWord
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	
	
Exception in thread "Thread-82" java.io.InvalidClassException: akka.persistence.r2dbc.state.DurableStateBySliceSpec; unable to create instance
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2183)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:839)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:828)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor352.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.io.ObjectStreamClass.lambda$newInstance$0(ObjectStreamClass.java:1097)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.io.ObjectStreamClass.newInstance(ObjectStreamClass.java:1105)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2180)
	... 26 more
Caused by: com.typesafe.config.ConfigException$Missing: merge of system properties,reference.conf @ jar:file:/Users/patrik/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.5/ssl-config-core_2.12-0.4.0.jar!/reference.conf: 1: No configuration setting found for key 'akka'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:149)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:262)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:348)
	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:406)
	at akka.actor.ActorSystem$Settings$.amendSlf4jConfig(ActorSystem.scala:336)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:817)
	at akka.actor.typed.ActorSystem$.createInternal(ActorSystem.scala:289)
	at akka.actor.typed.ActorSystem$.apply(ActorSystem.scala:204)
	at akka.actor.testkit.typed.scaladsl.ActorTestKit$.apply(ActorTestKit.scala:91)
	at akka.actor.testkit.typed.scaladsl.ActorTestKitBase.<init>(ActorTestKitBase.scala:36)
```

See also #19

**Comment by patriknw** [comment]
It's not a big deal, and I don't know what to do about it - closing
